// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/disaster37/go-centreon-rest/v21/api (interfaces: ServiceAPI)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/disaster37/go-centreon-rest/v21/models"
	gomock "github.com/golang/mock/gomock"
)

// MockServiceAPI is a mock of ServiceAPI interface.
type MockServiceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAPIMockRecorder
}

// MockServiceAPIMockRecorder is the mock recorder for MockServiceAPI.
type MockServiceAPIMockRecorder struct {
	mock *MockServiceAPI
}

// NewMockServiceAPI creates a new mock instance.
func NewMockServiceAPI(ctrl *gomock.Controller) *MockServiceAPI {
	mock := &MockServiceAPI{ctrl: ctrl}
	mock.recorder = &MockServiceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAPI) EXPECT() *MockServiceAPIMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockServiceAPI) Add(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockServiceAPIMockRecorder) Add(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockServiceAPI)(nil).Add), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockServiceAPI) Delete(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceAPIMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceAPI)(nil).Delete), arg0, arg1)
}

// DeleteCategories mocks base method.
func (m *MockServiceAPI) DeleteCategories(arg0, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategories", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategories indicates an expected call of DeleteCategories.
func (mr *MockServiceAPIMockRecorder) DeleteCategories(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategories", reflect.TypeOf((*MockServiceAPI)(nil).DeleteCategories), arg0, arg1, arg2)
}

// DeleteMacro mocks base method.
func (m *MockServiceAPI) DeleteMacro(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMacro", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMacro indicates an expected call of DeleteMacro.
func (mr *MockServiceAPIMockRecorder) DeleteMacro(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMacro", reflect.TypeOf((*MockServiceAPI)(nil).DeleteMacro), arg0, arg1, arg2)
}

// DeleteServiceGroups mocks base method.
func (m *MockServiceAPI) DeleteServiceGroups(arg0, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceGroups", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceGroups indicates an expected call of DeleteServiceGroups.
func (mr *MockServiceAPIMockRecorder) DeleteServiceGroups(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceGroups", reflect.TypeOf((*MockServiceAPI)(nil).DeleteServiceGroups), arg0, arg1, arg2)
}

// DeleteTraps mocks base method.
func (m *MockServiceAPI) DeleteTraps(arg0, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTraps", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTraps indicates an expected call of DeleteTraps.
func (mr *MockServiceAPIMockRecorder) DeleteTraps(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTraps", reflect.TypeOf((*MockServiceAPI)(nil).DeleteTraps), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockServiceAPI) Get(arg0, arg1 string) (*models.ServiceGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*models.ServiceGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceAPIMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceAPI)(nil).Get), arg0, arg1)
}

// GetCategories mocks base method.
func (m *MockServiceAPI) GetCategories(arg0, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockServiceAPIMockRecorder) GetCategories(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockServiceAPI)(nil).GetCategories), arg0, arg1)
}

// GetMacros mocks base method.
func (m *MockServiceAPI) GetMacros(arg0, arg1 string) ([]*models.Macro, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMacros", arg0, arg1)
	ret0, _ := ret[0].([]*models.Macro)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMacros indicates an expected call of GetMacros.
func (mr *MockServiceAPIMockRecorder) GetMacros(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMacros", reflect.TypeOf((*MockServiceAPI)(nil).GetMacros), arg0, arg1)
}

// GetParam mocks base method.
func (m *MockServiceAPI) GetParam(arg0, arg1 string, arg2 []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParam", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParam indicates an expected call of GetParam.
func (mr *MockServiceAPIMockRecorder) GetParam(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParam", reflect.TypeOf((*MockServiceAPI)(nil).GetParam), arg0, arg1, arg2)
}

// GetServiceGroups mocks base method.
func (m *MockServiceAPI) GetServiceGroups(arg0, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceGroups", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceGroups indicates an expected call of GetServiceGroups.
func (mr *MockServiceAPIMockRecorder) GetServiceGroups(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceGroups", reflect.TypeOf((*MockServiceAPI)(nil).GetServiceGroups), arg0, arg1)
}

// GetTraps mocks base method.
func (m *MockServiceAPI) GetTraps(arg0, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraps", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTraps indicates an expected call of GetTraps.
func (mr *MockServiceAPIMockRecorder) GetTraps(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraps", reflect.TypeOf((*MockServiceAPI)(nil).GetTraps), arg0, arg1)
}

// List mocks base method.
func (m *MockServiceAPI) List() ([]*models.ServiceGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*models.ServiceGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceAPIMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceAPI)(nil).List))
}

// SetCategories mocks base method.
func (m *MockServiceAPI) SetCategories(arg0, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCategories", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCategories indicates an expected call of SetCategories.
func (mr *MockServiceAPIMockRecorder) SetCategories(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCategories", reflect.TypeOf((*MockServiceAPI)(nil).SetCategories), arg0, arg1, arg2)
}

// SetMacro mocks base method.
func (m *MockServiceAPI) SetMacro(arg0, arg1 string, arg2 *models.Macro) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMacro", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMacro indicates an expected call of SetMacro.
func (mr *MockServiceAPIMockRecorder) SetMacro(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMacro", reflect.TypeOf((*MockServiceAPI)(nil).SetMacro), arg0, arg1, arg2)
}

// SetParam mocks base method.
func (m *MockServiceAPI) SetParam(arg0, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetParam", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetParam indicates an expected call of SetParam.
func (mr *MockServiceAPIMockRecorder) SetParam(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParam", reflect.TypeOf((*MockServiceAPI)(nil).SetParam), arg0, arg1, arg2, arg3)
}

// SetServiceGroups mocks base method.
func (m *MockServiceAPI) SetServiceGroups(arg0, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetServiceGroups", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetServiceGroups indicates an expected call of SetServiceGroups.
func (mr *MockServiceAPIMockRecorder) SetServiceGroups(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetServiceGroups", reflect.TypeOf((*MockServiceAPI)(nil).SetServiceGroups), arg0, arg1, arg2)
}

// SetTraps mocks base method.
func (m *MockServiceAPI) SetTraps(arg0, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTraps", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTraps indicates an expected call of SetTraps.
func (mr *MockServiceAPIMockRecorder) SetTraps(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTraps", reflect.TypeOf((*MockServiceAPI)(nil).SetTraps), arg0, arg1, arg2)
}
